anpr/urls.py
from django.urls import path

from . import views

app_name = "anpr"
urlpatterns = [
    path("", views.index, name="index"),
    path("<path:camera>/latest/", views.latest5, name="latest"),
    path("platesearch/", views.plate_search, name="plate_search"),
    path("platesearch/pdf", views.generate_EXCEL, name="generate_excel"),
    path("<path:camera>", views.convertRtspToHttp, name="convert"),
]
#     path("<str:camera>/convert/", views.convertRtspToHttp, name="convert"),
# ]

arima/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [path("admin/", admin.site.urls), path("anpr/", include("anpr.urls"))]

anpr/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models
from django.utils import timezone

class LicensePlates(models.Model):
    slno = models.AutoField(primary_key=True)
    camera_number = models.CharField(max_length=100)
    number_plate_number = models.CharField(max_length=50)
    image = models.CharField(max_length=100)
    date = models.DateTimeField()
    fullimage = models.CharField(max_length=100)

    class Meta:
        #managed = True
        db_table = "license_plates"

    def __str__(self):
        return self.number_plate_number


class Camera(models.Model):
    id = models.AutoField(primary_key=True)
    camera_number = models.CharField(max_length=100, help_text="Name of the Camera. AVOID SPACES IN THE NAME.")
    latitude = models.DecimalField(max_digits=10, decimal_places=7, help_text="Latitude of the Camera Location.")
    longitude = models.DecimalField(max_digits=10, decimal_places=7, help_text="Longitude of the Camera Location.")
    url = models.CharField(max_length=400, help_text="Functioning RTSP link(rtsp://localhost:8554/ds-test) or Path to Local Video(/home/user/vid.mp4). AVOID SPACES IN THE NAME.")
    plate_model = models.CharField(max_length=100, default = "T20-FP16",help_text="Name of the Plate Model. Refer to Accuracy Benchmarking Sheet if needed.")
    char_model = models.CharField(max_length=100, default = "chars-ssd",help_text="Name of the Chars Model. Refer to Accuracy Benchmarking Sheet if needed.")
    char_model_width = models.IntegerField(default = 304, help_text="Width of the Input to Char Model. Refer to Chars Training Documentation.")
    char_model_height = models.IntegerField(default = 192, help_text="Heigth of the Input to Char Model. Refer to Chars Training Documentation.")
    vid_width = models.IntegerField(default = 1920, help_text="Width of the Video Resolution.")
    vid_height = models.IntegerField(default = 1080, help_text="Heigth of the Video Resolution.")

    char_det_model = models.CharField(max_length=100, default = "CD2-FP32",help_text="Path to an .xml file with char detection model alone. Refer to Accuracy Benchmarking Sheet if needed.")
    char_recog_model = models.CharField(max_length=100, default = "CR1",help_text="Path to an .h5 and .json file with char recognition model alone. Refer to Accuracy Benchmarking Sheet if needed.")
    char_split = models.BooleanField(default=False, help_text="Tick to turn it on. Enables char model split into detection and recognition")


    plate_threshold = models.DecimalField(max_digits=10, decimal_places=1, default=0.4, help_text="Threshold for Plate Detection.")
    character_threshold = models.DecimalField(max_digits=10, decimal_places=1, default=0.4, help_text="Threshold for Character Detection and Recognition.")
    plate_interval = models.IntegerField(default = 5, help_text="Inference Interval for Plate Detection.")
    roi_y_min = models.IntegerField(default = 0, help_text="ROI_Y Minimum value from Top. Inference will happen only in [(xmin,ymin),(xmax,ymin),(xmin,ymax),(xmax,ymax)]-(Origin at the top left corner).")
    roi_x_min = models.IntegerField(default = 0, help_text="ROI_X Minimum value from Left. Inference will happen only in [(xmin,ymin),(xmax,ymin),(xmin,ymax),(xmax,ymax)]-(Origin at the top left corner).")
    roi_y_max = models.IntegerField(default = 1080, help_text="ROI_Y Maximum value from Top. Inference will happen only in [(xmin,ymin),(xmax,ymin),(xmin,ymax),(xmax,ymax)]-(Origin at the top left corner).")
    roi_x_max = models.IntegerField(default = 1980, help_text="ROI_X Maximum value from Left. Inference will happen only in [(xmin,ymin),(xmax,ymin),(xmin,ymax),(xmax,ymax)]-(Origin at the top left corner).")
    nireq = models.IntegerField(default = 1, help_text="Number of Inference Requests for plate detection. It is usually the number of streams.")

    object_tracking = models.CharField(max_length=100, default = "short-term",help_text="short-term/zero-term/off - Enable Object Tracking.")
    post_processing_method = models.IntegerField(default = 15, help_text="Post-processing Method - 1 to 21. Refer to AB2 for details.")
    cluster_end = models.IntegerField(default = 30, help_text="Y-axis value beyond which we delcare that vehicle has passed and the cluster has ended. 0 means end of ROI- but then full image of vehicle will be missed. So a value of 20-60 is ideal i.e, save image when plate is at 20 pixels away from top x-axis. This is the same as RLVD. Set it to 0 to disable this.")
    cluster_end_vehicle = models.IntegerField(default = 10, help_text="Number of plates in a vehicle cluster beyond which we declare that the cluster has ended and start post-processing. This feature is EXPERIMENTAL and was added to handle STATIC VEHICLES. A value of 10 means, if 10 plates are detected in a vehicle cluster, then plate detection is stopped and post-processing starts. Set it to a high value(100) to disable. Both cluster_end and cluster_end_vehicle are used to end clusters.")
    no_of_active_vehicles = models.IntegerField(default = 3, help_text="Number of vehilces in the done_tracking_ids at a time. Rest will be popped to clear repetition of ids. This parameter was added to counter choppiness.")


    extras = models.IntegerField(default = -3, help_text="Extra pixels that we manually add to the cropped plate. Increasing this leads to coloured boundingbox in saved image. This is a potential bug - have to change gvawatermark if needed.")
    full_image_save_quality = models.IntegerField(default = 20, help_text="Cv2.Write Quaility of Image.Lesser the quality, lesser the storage space needed. Range of 0-99.")
    cropped_image_save_quality = models.IntegerField(default = 60, help_text="Cv2.Write Quaility of Image.Lesser the quality, lesser the storage space needed. Range of 0-99.")

    video_display = models.BooleanField(default=False, help_text="Tick to turn it on. Enables video display with bounding boxes and FPS for debugging purposes. Remember to disable before Deployment.")
    

    class Meta:
        #managed = True
        db_table = "camera_config"

    def __str__(self):
        return self.camera_number


class GuardianParameters(models.Model):

    id = models.AutoField(primary_key=True)
    records_deletion_days = models.IntegerField(default = 10, help_text="Number of days of Records to be present in the Database.")
    images_deletion_days = models.IntegerField(default = 7, help_text="Number of days of Images to present in the Device.")



    class Meta:
        #managed = True
        verbose_name = 'GuardianParameter'
        db_table = "guardian_parameters"

    def __str__(self):
        return "Parameters"

anpr/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseBadRequest
from django.db.models.functions import Length
from django.db.models import Count
import json
import os
import xlsxwriter
import PIL.Image as Image
from .models import LicensePlates, Camera
from .common.validators import is_valid, get_status_date_time
from .common.functional_utils import get_filtered_data
from .common.file_utils import create_excel
from subprocess import Popen
global camname
from datetime import datetime
import logging


django_dir = os.environ['DJANGOPATH']#"/home/user/Django_Anpr-master/" # Directory containing Django manage.py
logs_dir = os.environ['LOGSPATH']#"/home/"+str(os.environ.get('USER'))+"/logs/"# Directory to store log files and the log file format
if not os.path.exists(logs_dir):# Create Directory if it doesn't exist
    os.makedirs(logs_dir)
logging.basicConfig(filename=logs_dir+"django.log", level=logging.INFO,
    format=("%(asctime)s - %(levelname)s:%(process)d:%(processName)s:%(filename)s - Function Name:%(funcName)s - Line No:%(lineno)d - %(message)s  "))
#logging.info("STARTED DJANGO SERVER")


# Create your views here.
#def power_off(request):
#    if request.POST:
#      print("Shutting Down")
#    return render(request,'index.html',{})

def index(request):
    cameraQuerySet = Camera.objects.all()
    cameras = []
    for cam in cameraQuerySet:
        temp = {}
        temp["id"] = cam.id
        temp["camera_number"] = cam.camera_number
        temp["latitude"] = str(cam.latitude)
        temp["longitude"] = str(cam.longitude)
        temp["url"] = cam.url
        cameras.append(temp)

    count = LicensePlates.objects.count()

    licensePlates = LicensePlates.objects.filter(
        camera_number=cameras[0]["camera_number"]
    ).order_by("-slno")[:5]
    #for lp in licensePlates:
    #    lp.image = "anpr/" + lp.image

    return render(
        request,
        "anpr/index.html",
        {
            "count": count,
            "licensePlates": licensePlates,
            "cameraJSON": json.dumps(cameras),
            "cameras": cameras,
            "selectedCamera": cameras[0],
        },
    )


def latest5(request, camera):
    #print(camera)
    count = LicensePlates.objects.count()
    licensePlates = LicensePlates.objects.filter(camera_number=camera).order_by("-slno")\
    .annotate(text_len=Length('number_plate_number')).filter(text_len__gt=5).filter(text_len__lt=12)[:5]

    #https://books.agiliq.com/projects/django-orm-cookbook/en/latest/distinct.html
    #distinct = LicensePlates.objects.filter(camera_number=camera).values('number_plate_number').distinct()#.order_by("-slno")\
    #.annotate(text_len=Length('number_plate_number')).filter(text_len__gt=5).values('number_plate_number').\
    #annotate(name_count=Count('number_plate_number')).filter(name_count=1)
    #records = User.objects.filter(first_name__in=[item['first_name'] for item in distinct])
    #licensePlates = LicensePlates.objects.filter(camera_number=camera).order_by("-slno")\
    #.annotate(text_len=Length('number_plate_number')).filter(text_len__gt=5).\
    #filter(number_plate_number__in=[item['number_plate_number'] for item in distinct])[:5]#.distinct()[:5]
    #staff = LicensePlates.objects.all().values('number_plate_number').distinct()
    #print(staff.query)
    #for item in staff:
    #	print("ITEM",item)
    #print(staff[:5])
    #ids = licensePlates.values_list('number_plate_number', flat=True).distinct()[:5]																																											
    #print(ids)
    #print("Plates",plates)
    #licensePlates = LicensePlates.objects.filter(camera_number=camera).order_by(
    #    "-slno"
    #)[:5]
    #print(licensePlates)
    #for lp in licensePlates:
    #    lp.image = "anpr/" + lp.image

    return render(
        request, "anpr/latest5.html", {"licensePlates": licensePlates, "count": count}
    )


def plate_search(request):
    # get camera name list for dropdown
    logging.info("Plate Search - Start")
    cameraQuerySet = Camera.objects.all()
    cameras = []
    cam_temp = {}
    cam_temp["id"] = "0"
    cam_temp["name"] = "All"
    cameras.append(cam_temp)
    for camera in cameraQuerySet:
        temp = {}
        temp["id"] = camera.id
        temp["name"] = camera.camera_number
        temp["latitude"] = str(camera.latitude)
        temp["longitude"] = str(camera.longitude)
        cameras.append(temp)

    if request.method == "GET":
        form_data = request.GET
        #print("form_data", form_data)
        if len(form_data.keys()) == 0:
            return render(request, "anpr/plate_search.html", {"cameras": cameras})
            logging.info("Plate Search - End")

        try:
            date_time_availability = get_status_date_time(
                form_data["start_date_time"], form_data["end_date_time"]
            )
            if is_valid(form_data, date_time_availability):
                #print("Searching Records... ")
                #print("Continuous Plate Records")
                license_plates_continous_order_plate_number = get_filtered_data(
                    form_data, date_time_availability, "continuous"
                )
                if form_data["vehicle_no"]:
                    #print("Random Plate Records", form_data["vehicle_no"], len(form_data["vehicle_no"]))
                    license_plate_random_order_plate_number = get_filtered_data(form_data, date_time_availability, "random")
                    license_plates = license_plates_continous_order_plate_number+license_plate_random_order_plate_number
                else:
                    license_plates = license_plates_continous_order_plate_number
                logging.info("Plate Search - End")
                return render(
                    request,
                    "anpr/plate_search.html",
                    {
                        "license_plates": license_plates,
                        "cameras": cameras,
                        "cameraJSON": json.dumps(cameras),
                        "filter_conditions": form_data,
                    },
                )
        except Exception as e:
            if e.args[0] == "VEHICLE_NO_INVALID":
                print("Invalid Data")
                error = "Vehicle No exists the char limit."
            elif e.args[0] == "DATE_TIME_RANGE_INVALID":
                print("Invalid Data")
                error = "Start Date/Time is greater than End Date/Time."
            else:
                print("error", e.args[0])
                error = "Oops! Something went wrong."
            logging.error("PLATE SEARCH ERROR:"+str(error))
            logging.info("Plate Search - End")
            return render(
                request, "anpr/plate_search.html", {"error": error, "cameras": cameras,}
            )
    else:
        logging.info("Plate Search - End")
        return HttpResponseBadRequest("Bad Request!")
    logging.info("Plate Search - End")

def generate_EXCEL(request):
    form_data = request.GET
    #print("Generating excel...")
    try:
        date_time_availability = get_status_date_time(
            form_data["start_date_time"], form_data["end_date_time"]
        )
        if is_valid(form_data, date_time_availability):
            license_plates_continous_order_plate_number = get_filtered_data(
                form_data, date_time_availability, "continuous"
            )
            license_plate_random_order_plate_number = get_filtered_data(
                form_data, date_time_availability, "random"
            )
            contents = (
                license_plates_continous_order_plate_number
                + license_plate_random_order_plate_number
            )
        headers = ["Sl. No", "Camera Name", "Plate Number", "Capture Time", "Image"]
        #filename = "vehicles_list.xlsx"
        #print(form_data)
        # get camera name for camera id
        cameras = Camera.objects.all()
        camera_id = form_data['selected_camera']
        if(int(camera_id) == 0):
            camera_name = "All"
        else:
            camera = Camera.objects.get(pk=camera_id)
            camera_name = camera.camera_number
        filename = "Camera-"+camera_name+"-"#+"---PLATENUMBER---"+form_data['vehicle_no']
        if(form_data["start_date_time"]):
            filename = filename + datetime.strptime(form_data["start_date_time"], '%Y-%m-%dT%H:%M').strftime("%d%b%y-%H.%M")
        if(form_data["end_date_time"]):
            filename = filename + "-to-" + datetime.strptime(form_data["end_date_time"], '%Y-%m-%dT%H:%M').strftime("%d%b%y-%H.%M")+ ".xlsx"
        else:
            filename = filename + ".xlsx"    
        #print(form_data['vehicle_no']+"_"+camera_name+"_"+form_data["start_date_time"].replace("T","_")+"_"+form_data["end_date_time"].replace("T","_"))
        create_excel(filename, contents, headers)
    except xlsxwriter.exceptions.FileCreateError as e:
        # For Python 3 use input() instead of raw_input().
        #print("Excel Creation Error",str(e))
        logging.error("EXCEL WRITING ERROR :"+str(e))
        decision = input(
            "Exception caught in workbook.close(): %s\n"
            "Please close the file if it is open in Excel.\n"
            "Try to write file again? [Y/n]: " % e
        )
        return HttpResponseBadRequest(decision)
    except Exception as e:
        logging.error("EXCEL INVALID DATA ERROR :"+str(e))
        #print("Invalid Filter Data")
        return HttpResponseBadRequest("Invalid Filter Data")
    #print("Excel generated successfully.")
    return HttpResponse("Success")
    
    
#from .mjpg_serve import actualConvert
def convertRtspToHttp(request,camera):
    # #print("Passed Camera",camera)
    # try:
    #     pid.kill()
    #     #print("Killed process",pid)
    # except Exception as e:
    #     print("Exception while killing",str(e))
    print("Views Camname", camera)

anpr/templates/anpr/index-fit-iframe-full-2.html
<!DOCTYPE html>
<html>
  <head>
    {% load static %}
    <title>ANPR</title>
    

    <!--link
      href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,700"
      rel="stylesheet"
    /-->

    <!--link
      rel="stylesheet"
      href="/home/god2/dproject/django_env/latest_arima/arima/anpr/static/anpr/lib/leaflet/leaflet.css"
      integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ=="
      crossorigin=""
    />
    <script
      src="/home/god2/dproject/django_env/latest_arima/arima/anpr/static/anpr/lib/leaflet/leaflet.js"
      integrity="sha512-gZwIG9x3wUXg2hdXF6+rVkLF/0Vi9U8D2Ntg4Ga5I5BZpVkVxlJWbSQtXPSiUTtC0TjtGOmxa1AJPuV0CPthew=="
      crossorigin=""
    ></script-->
    <link rel="icon" href="{% static 'anpr/static/anpr/images/logo99.png' %}" type="image/x-icon">
    <link href="{% static 'anpr/css/fonts.css' %}" rel="stylesheet" />
    <link href="{% static 'anpr/lib/leaflet/leaflet.css' %}" rel="stylesheet" /> 
    <script src="{% static 'anpr/lib/leaflet/leaflet.js' %}"> </script>
    <link href="{% static 'anpr/css/center.css' %}" rel="stylesheet" />
    <link href="{% static 'anpr/css/index.css' %}" rel="stylesheet" />

    <script>
    function rtspToHttp(camNum)
    {
    console.log("Converting");
    console.log(camNum)
        var xhttp = new XMLHttpRequest();
        xhttp.onreadystatechange = function () {
          if (this.readyState == 4 && this.status == 200) {
          console.log("Converted");
          //location.reload();
          setTimeout(() =>
          {console.log("Running"); const iframe = document.getElementById("feed");
          iframe.src=iframe.src;}, 10000)
          }
          
        };
        //xhttp.open(
        // "GET",
        // "{% url 'anpr:convert' 'camera' %}".replace("camera", camNum),
        //  true
        xhttp.open(
          "GET",
          "{% url 'anpr:convert' 'camera' %}".replace("camera", camNum),
          true
        );
        xhttp.send();
      }
      function fetchLatest() {
        console.log("fetching");
        var xhttp = new XMLHttpRequest();
        xhttp.onreadystatechange = function () {
          if (this.readyState == 4 && this.status == 200) {
            document.getElementById("Latest5").innerHTML = this.responseText;
            document.getElementById(
              "count"
            ).innerText = document.getElementById("latestCount").innerText;
          }
        };
        var camera_number = document.getElementById("currCamera").innerText;
        xhttp.open(
          "GET",
          "{% url 'anpr:latest' 'camNum' %}".replace("camNum", camera_number),
          true
        );
        xhttp.send();
      }
      var cameraList = JSON.parse("{{cameraJSON|escapejs}}");
      rtspToHttp(cameraList[0].url);
      console.log(cameraList[0].url);
      // UNCOMMENT ONCE DONE
      setInterval(fetchLatest, 2000);

      function openFullImage(path, license) {
        console.log(path, license);
        document.getElementById("modalImage").src =  path;
        document.getElementById("modalLicense").innerText = license;
        document.getElementById("modal").style.display = "flex";
      }

      function closeModal() {
        document.getElementById("modal").style.display = "none";
      }

      function toggleView() {
        setTimeout(function () {
          mymap.invalidateSize(true);
        });
        let feed = document.getElementById("liveFeed");
        let cameraSelector = document.getElementById("cameraSelector");

        if (feed.style.display == "none") {
          feed.style.display = "flex";
          cameraSelector.style.display = "none";
        } else {
          feed.style.display = "none";
          cameraSelector.style.display = "flex";
        }
      }
      var modal = document.getElementById("modal");
      window.onclick = function (event) {
        if (event.target == modal) {
          modal.style.display = "none";
        }
      };
    </script>

    <style>
      html,
      body {
        height: 100%;
        border: 2px solid #111111;
      }

      .body-container {
        display: flex;
        flex-direction: row;
        height: 100%;
      }
      .company-icon {
        position: absolute;
        left: 0;
      }
      .company-title {
        text-align: center;
      }

      .navbar {
        padding: 10px 10px;
        display: flex;
        flex-direction: column;
      }
      .navbar a {
        display: flex;
        align-items: center;
        margin: 10px 0px;
      }
      .navbar img {
        float: left;
      }
      .navbar span {
        padding-left: 10px;
        font-size: 26px;
      }
      .topbar-element {
        display: flex;
        align-items: center;
      }
      .content {
        flex: 8;
        display: flex;
        flex-direction: column;
        height: 100%;
      }
      .power-button {
        width: 50px;
      }
      .center-content {
        width: 100%;
        flex: 2;
        display: flex;
        flex-direction: row;
        overflow: hidden;
      }
      #liveFeed {
        width: 100%;
        align-items: center;
        justify-content: center;
        background-color: grey;
        height: 100%;
        overflow: hidden;
      }
      #feed {
        overflow: hidden
        height: 100%;
        width: 100%;
        top: 0;
        left: 0;
        border: 0;
      }
      #cameraSelector {
        width: 100%;
        display: none;
        flex-direction: row;
        height: 100%;
      }
      .marker {
        border: none;
        cursor: pointer;
        height: 32px;
        width: 32px;
        background-image: url("{% static 'anpr/images/placeholder.png' %}");
        background-color: rgba(0, 0, 0, 0);
      }

      #closeButton:hover {
        color: grey;
        cursor: pointer;
      }

      .plate-popup {
        display: none;
        position: absolute;
        width: 100%;
        height: 100%;
        justify-content: center;
        align-items: center;
        background: rgba(0, 0, 0, 0.8);
        z-index: 10000;
      }

      .plate-popup-flex-container {
        background-color: #dcdcdc;
        box-shadow: 10px 10px 60px #555;
        display: flex;
        flex-direction: column;
        align-items: center;
        width: 60%;
        height: 80%;
        position: relative;
        border-radius: 8px;
        padding: 15px 15px;
      }

      .popup-close-button {
        background-color: #fff;
        border: 3px solid #999;
        border-radius: 50px;
        cursor: pointer;
        font-family: arial;
        font-weight: bold;
        position: absolute;
        top: -15px;
        right: -15px;
        font-size: 25px;
        line-height: 30px;
        width: 30px;
        height: 30px;
        text-align: center;
      }

      .popup-close-button:hover {
        background-color: #ccc;
      }
      button,
      img {
        cursor: pointer;
      }
    </style>
  </head>
  <body>
    <div id="modal" class="plate-popup">
      <div class="plate-popup-flex-container">
        <div>
          <span class="popup-close-button" onclick="closeModal('modal')"
            >&times;</span
          >
          <span id="modalLicense" style="font-size: x-large;">TN94657</span>
        </div>
        <img id="modalImage" width="100%" height="90%" />
      </div>
    </div>
    <div class="body-container">
      <div class="sidenav">
        <div class="company">
          <img class="company-icon" src="{% static 'anpr/images/logo1.png' %}" />
          <!--span class="company-title">ARIMA</span-->
        </div>
        <div class="navbar">
          <a style="color: #f1f1f1;"
            ><img src="{% static 'anpr/images/clipboard.png' %}" />
            <b><span style="font-family:helvetica;font-size:16px;">DASHBOARD</span></b></a
          >
          <a href="{% url 'anpr:plate_search' %}"
            ><img src="{% static 'anpr/images/search4.png' %}" />
            <b><span style="font-family:helvetica;font-size:16px">PLATESEARCH</span></b></a
          >
          <a
            ><img src="{% static 'anpr/images/car.png' %}" />
            <b><span onclick="alert('This feature has not been unlocked.')"
              style="font-family:helvetica;font-size:16px">VAAHANSEARCH</span
            ></b></a
          >
        </div>
      </div>
      <div class="content">
        <div class="topbar">
          <button
            class="topbar-element"
            style="flex: 3;border-width:2px;border-style:solid;border-color:black;"
            onclick="toggleView()"
          >
            <span class="label" style="font-family:Courier" >CAMERAS </span>
            <span class="number" style="font-family:Courier;color:black">{{cameras|length}}</span>
            <img src="{% static 'anpr/images/dropdown.png' %}" style="height:30px"/>
          </button>
          <div class="topbar-element" style="flex: 4;border-width:2px;border-style:solid;border-color:black;">
            <span class="label" style="font-family:Courier;color:black">DETECTIONS </span>
            <span id="count" class="number" style="font-family:Courier;color:black">{{count}}</span>
          </div>
          <div
            class="topbar-element"
            style="flex: 3; border-left: 1px solid black;border-width:2px;border-style:solid;border-color:black;"
          >
            <span class="label" id="currCamera" style="font-family:Courier;color:black"
              >{{cameras.0.camera_number}}</span
            >
          </div>
          <!--button class="power-button" type="submit" style="border-width:2px;border-style:solid;border-color:black;">
            <img src="{% static 'anpr/images/switch.png' %}" />
          </button-->
        </div>
        <div class="center-content">
          <div id="liveFeed" style="border-width:5px;border-style:solid;border-color:black;">
            <iframe
              id="feed"
              src="http://127.0.0.1:9090/cam.mjpg"
              frameborder="0"
              allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
              allowfullscreen
              
              
            ></iframe>
          </div>
          <div id="cameraSelector">
            <div class="sidebar">
              <div id="listings" class="listings">
                {% for cam in cameras %}
                <div id="listing-{{cam.id}}" class="item">
                  <a href="#" class="title" style="font-size:20px" id="link-{{cam.id}}"
                    >{{cam.camera_number}}</a
                  >
                </div>
                {% endfor %}
              </div>
            </div>
            <div id="map" class="map"></div>
            <script>
              var mymap = L.map("map", {
                center: [13.0827, 80.2707],
                scrollWheelZoom: false,
              }).setView([13.0827, 80.2707], 14);
              var url = "{% static 'anpr/MapTiles' %}";
              L.tileLayer(url + "/{z}/{x}/{y}.png", {
                minZoom: 14,
                maxZoom: 14,
                tileSize: 512,
                zoomOffset: -1,
              }).addTo(mymap);

              var cameraList = JSON.parse("{{cameraJSON|escapejs}}");

              document
                .getElementById(`listing-${cameraList[0].id}`)
                .classList.add("active");

              function addMarkers() {
                var myIcon = L.icon({
                  iconUrl: "{% static 'anpr/images/placeholder.png' %}",
                  iconSize: [32, 32],
                });
                cameraList.forEach((camera) => {
                  var marker = L.marker([camera.latitude, camera.longitude], {
                    icon: myIcon,
                  }).addTo(mymap);
                  var popup = marker.bindPopup(
                    `<span style="width:100%; text-align:center" >${camera.camera_number}</span>`
                  );

                  var onclick = () => {
                    mymap.flyTo([camera.latitude, camera.longitude]);
                    popup.openPopup();
                    var activeItem = document.getElementsByClassName("active");
                    //e.stopPropagation();
                    if (activeItem[0]) {
                      activeItem[0].classList.remove("active");
                    }
                    var listing = document.getElementById(
                      "listing-" + camera.id
                    );
                    listing.classList.add("active");
                  };

                  marker.on("click", onclick);
                  var link = document.getElementById("link-" + camera.id);
                  link.addEventListener("click", () => {
                    document.getElementById("currCamera").innerText =
                      camera.camera_number;
                      rtspToHttp(camera.url);
                    //document.getElementById("feed").src = "http://127.0.0.1:9090/cam.mjpg";//camera.url;
                    onclick();
                  });
                });
              }
              addMarkers();
            </script>
          </div>
        </div>
        <div
          id="Latest5"
          class="Last5"
          style="display: flex; flex-direction: row;"
        >
          {% for lp in licensePlates %}
          <div
            class="latest"
            onclick="openFullImage('{% static lp.fullimage %}', '{{lp.number_plate_number}}')"
          >
            <div class="snap">
              <img src="{% static lp.image %}" width="100%" height="150px" />
            </div>
            <div class="output" style="color:black"><b>{{lp.number_plate_number}}</b></div>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </body>
</html>