anpr/urls.py
from django.urls import path

from . import views

app_name = "anpr"
urlpatterns = [
    path("", views.index, name="index"),
    path("<path:camera>/latest/", views.latest5, name="latest"),
    path("platesearch/", views.plate_search, name="plate_search"),
    path("platesearch/pdf", views.generate_EXCEL, name="generate_excel"),
    path("<path:camera>", views.convertRtspToHttp, name="convert"),
]
#     path("<str:camera>/convert/", views.convertRtspToHttp, name="convert"),
# ]

arima/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [path("admin/", admin.site.urls), path("anpr/", include("anpr.urls"))]

oldanpr/urls.py
from django.urls import path

from . import views

app_name = "anpr"
urlpatterns = [
    path("", views.index, name="index"),
    path("<str:camera>/latest/", views.latest5, name="latest"),
    path("platesearch/", views.plate_search, name="plate_search"),
    path("platesearch/pdf", views.generate_EXCEL, name="generate_excel"),
]

anpr/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseBadRequest
from django.db.models.functions import Length
from django.db.models import Count
import json
import os
import xlsxwriter
import PIL.Image as Image
from .models import LicensePlates, Camera
from .common.validators import is_valid, get_status_date_time
from .common.functional_utils import get_filtered_data
from .common.file_utils import create_excel
from subprocess import Popen
global camname
from datetime import datetime
import logging


django_dir = os.environ['DJANGOPATH']#"/home/user/Django_Anpr-master/" # Directory containing Django manage.py
logs_dir = os.environ['LOGSPATH']#"/home/"+str(os.environ.get('USER'))+"/logs/"# Directory to store log files and the log file format
if not os.path.exists(logs_dir):# Create Directory if it doesn't exist
    os.makedirs(logs_dir)
logging.basicConfig(filename=logs_dir+"django.log", level=logging.INFO,
    format=("%(asctime)s - %(levelname)s:%(process)d:%(processName)s:%(filename)s - Function Name:%(funcName)s - Line No:%(lineno)d - %(message)s  "))
#logging.info("STARTED DJANGO SERVER")


# Create your views here.
#def power_off(request):
#    if request.POST:
#      print("Shutting Down")
#    return render(request,'index.html',{})

def index(request):
    cameraQuerySet = Camera.objects.all()
    cameras = []
    for cam in cameraQuerySet:
        temp = {}
        temp["id"] = cam.id
        temp["camera_number"] = cam.camera_number
        temp["latitude"] = str(cam.latitude)
        temp["longitude"] = str(cam.longitude)
        temp["url"] = cam.url
        cameras.append(temp)

    count = LicensePlates.objects.count()

    licensePlates = LicensePlates.objects.filter(
        camera_number=cameras[0]["camera_number"]
    ).order_by("-slno")[:5]
    #for lp in licensePlates:
    #    lp.image = "anpr/" + lp.image

    return render(
        request,
        "anpr/index.html",
        {
            "count": count,
            "licensePlates": licensePlates,
            "cameraJSON": json.dumps(cameras),
            "cameras": cameras,
            "selectedCamera": cameras[0],
        },
    )


def latest5(request, camera):
    #print(camera)
    count = LicensePlates.objects.count()
    licensePlates = LicensePlates.objects.filter(camera_number=camera).order_by("-slno")\
    .annotate(text_len=Length('number_plate_number')).filter(text_len__gt=5).filter(text_len__lt=12)[:5]

    #https://books.agiliq.com/projects/django-orm-cookbook/en/latest/distinct.html
    #distinct = LicensePlates.objects.filter(camera_number=camera).values('number_plate_number').distinct()#.order_by("-slno")\
    #.annotate(text_len=Length('number_plate_number')).filter(text_len__gt=5).values('number_plate_number').\
    #annotate(name_count=Count('number_plate_number')).filter(name_count=1)
    #records = User.objects.filter(first_name__in=[item['first_name'] for item in distinct])
    #licensePlates = LicensePlates.objects.filter(camera_number=camera).order_by("-slno")\
    #.annotate(text_len=Length('number_plate_number')).filter(text_len__gt=5).\
    #filter(number_plate_number__in=[item['number_plate_number'] for item in distinct])[:5]#.distinct()[:5]
    #staff = LicensePlates.objects.all().values('number_plate_number').distinct()
    #print(staff.query)
    #for item in staff:
    #	print("ITEM",item)
    #print(staff[:5])
    #ids = licensePlates.values_list('number_plate_number', flat=True).distinct()[:5]																																											
    #print(ids)
    #print("Plates",plates)
    #licensePlates = LicensePlates.objects.filter(camera_number=camera).order_by(
    #    "-slno"
    #)[:5]
    #print(licensePlates)
    #for lp in licensePlates:
    #    lp.image = "anpr/" + lp.image

    return render(
        request, "anpr/latest5.html", {"licensePlates": licensePlates, "count": count}
    )


def plate_search(request):
    # get camera name list for dropdown
    logging.info("Plate Search - Start")
    cameraQuerySet = Camera.objects.all()
    cameras = []
    cam_temp = {}
    cam_temp["id"] = "0"
    cam_temp["name"] = "All"
    cameras.append(cam_temp)
    for camera in cameraQuerySet:
        temp = {}
        temp["id"] = camera.id
        temp["name"] = camera.camera_number
        temp["latitude"] = str(camera.latitude)
        temp["longitude"] = str(camera.longitude)
        cameras.append(temp)

    if request.method == "GET":
        form_data = request.GET
        #print("form_data", form_data)
        if len(form_data.keys()) == 0:
            return render(request, "anpr/plate_search.html", {"cameras": cameras})
            logging.info("Plate Search - End")

        try:
            date_time_availability = get_status_date_time(
                form_data["start_date_time"], form_data["end_date_time"]
            )
            if is_valid(form_data, date_time_availability):
                #print("Searching Records... ")
                #print("Continuous Plate Records")
                license_plates_continous_order_plate_number = get_filtered_data(
                    form_data, date_time_availability, "continuous"
                )
                if form_data["vehicle_no"]:
                    #print("Random Plate Records", form_data["vehicle_no"], len(form_data["vehicle_no"]))
                    license_plate_random_order_plate_number = get_filtered_data(form_data, date_time_availability, "random")
                    license_plates = license_plates_continous_order_plate_number+license_plate_random_order_plate_number
                else:
                    license_plates = license_plates_continous_order_plate_number
                logging.info("Plate Search - End")
                return render(
                    request,
                    "anpr/plate_search.html",
                    {
                        "license_plates": license_plates,
                        "cameras": cameras,
                        "cameraJSON": json.dumps(cameras),
                        "filter_conditions": form_data,
                    },
                )
        except Exception as e:
            if e.args[0] == "VEHICLE_NO_INVALID":
                print("Invalid Data")
                error = "Vehicle No exists the char limit."
            elif e.args[0] == "DATE_TIME_RANGE_INVALID":
                print("Invalid Data")
                error = "Start Date/Time is greater than End Date/Time."
            else:
                print("error", e.args[0])
                error = "Oops! Something went wrong."
            logging.error("PLATE SEARCH ERROR:"+str(error))
            logging.info("Plate Search - End")
            return render(
                request, "anpr/plate_search.html", {"error": error, "cameras": cameras,}
            )
    else:
        logging.info("Plate Search - End")
        return HttpResponseBadRequest("Bad Request!")
    logging.info("Plate Search - End")

def generate_EXCEL(request):
    form_data = request.GET
    #print("Generating excel...")
    try:
        date_time_availability = get_status_date_time(
            form_data["start_date_time"], form_data["end_date_time"]
        )
        if is_valid(form_data, date_time_availability):
            license_plates_continous_order_plate_number = get_filtered_data(
                form_data, date_time_availability, "continuous"
            )
            license_plate_random_order_plate_number = get_filtered_data(
                form_data, date_time_availability, "random"
            )
            contents = (
                license_plates_continous_order_plate_number
                + license_plate_random_order_plate_number
            )
        headers = ["Sl. No", "Camera Name", "Plate Number", "Capture Time", "Image"]
        #filename = "vehicles_list.xlsx"
        #print(form_data)
        # get camera name for camera id
        cameras = Camera.objects.all()
        camera_id = form_data['selected_camera']
        if(int(camera_id) == 0):
            camera_name = "All"
        else:
            camera = Camera.objects.get(pk=camera_id)
            camera_name = camera.camera_number
        filename = "Camera-"+camera_name+"-"#+"---PLATENUMBER---"+form_data['vehicle_no']
        if(form_data["start_date_time"]):
            filename = filename + datetime.strptime(form_data["start_date_time"], '%Y-%m-%dT%H:%M').strftime("%d%b%y-%H.%M")
        if(form_data["end_date_time"]):
            filename = filename + "-to-" + datetime.strptime(form_data["end_date_time"], '%Y-%m-%dT%H:%M').strftime("%d%b%y-%H.%M")+ ".xlsx"
        else:
            filename = filename + ".xlsx"    
        #print(form_data['vehicle_no']+"_"+camera_name+"_"+form_data["start_date_time"].replace("T","_")+"_"+form_data["end_date_time"].replace("T","_"))
        create_excel(filename, contents, headers)
    except xlsxwriter.exceptions.FileCreateError as e:
        # For Python 3 use input() instead of raw_input().
        #print("Excel Creation Error",str(e))
        logging.error("EXCEL WRITING ERROR :"+str(e))
        decision = input(
            "Exception caught in workbook.close(): %s\n"
            "Please close the file if it is open in Excel.\n"
            "Try to write file again? [Y/n]: " % e
        )
        return HttpResponseBadRequest(decision)
    except Exception as e:
        logging.error("EXCEL INVALID DATA ERROR :"+str(e))
        #print("Invalid Filter Data")
        return HttpResponseBadRequest("Invalid Filter Data")
    #print("Excel generated successfully.")
    return HttpResponse("Success")
    
    
#from .mjpg_serve import actualConvert
def convertRtspToHttp(request,camera):
    # #print("Passed Camera",camera)
    # try:
    #     pid.kill()
    #     #print("Killed process",pid)
    # except Exception as e:
    #     print("Exception while killing",str(e))
    print("Views Camname", camera)

oldanpr/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseBadRequest
import json

from .models import LicensePlates, Camera
from .common.validators import is_valid, get_status_date_time
from .common.functional_utils import get_filtered_data
from .common.file_utils import create_excel

# Create your views here.


def index(request):
    cameraQuerySet = Camera.objects.all()
    cameras = []
    for cam in cameraQuerySet:
        temp = {}
        temp["id"] = cam.id
        temp["camera_number"] = cam.camera_number
        temp["latitude"] = str(cam.latitude)
        temp["longitude"] = str(cam.longitude)
        temp["url"] = cam.url
        cameras.append(temp)

    count = LicensePlates.objects.count()

    licensePlates = LicensePlates.objects.filter(
        camera_number=cameras[0]["camera_number"]
    ).order_by("-slno")[:5]
    for lp in licensePlates:
        lp.image = "anpr/" + lp.image

    return render(
        request,
        "anpr/index.html",
        {
            "count": count,
            "licensePlates": licensePlates,
            "cameraJSON": json.dumps(cameras),
            "cameras": cameras,
            "selectedCamera": cameras[0],
        },
    )


def latest5(request, camera):
    print(camera)
    count = LicensePlates.objects.count()
    licensePlates = LicensePlates.objects.filter(camera_number=camera).order_by(
        "-slno"
    )[:5]
    for lp in licensePlates:
        lp.image = "anpr/" + lp.image

    return render(
        request, "anpr/latest5.html", {"licensePlates": licensePlates, "count": count}
    )


def plate_search(request):
    # get camera name list for dropdown
    cameraQuerySet = Camera.objects.all()
    cameras = []
    t = {}
    t["id"] = "0"
    t["name"] = "All"
    cameras.append(t)
    for camera in cameraQuerySet:
        temp = {}
        temp["id"] = camera.id
        temp["name"] = camera.camera_number
        temp["latitude"] = str(camera.latitude)
        temp["longitude"] = str(camera.longitude)
        cameras.append(temp)

    if request.method == "GET":
        form_data = request.GET
        print("form_data", form_data)
        if len(form_data.keys()) == 0:
            return render(request, "anpr/plate_search.html", {"cameras": cameras,})
        try:
            date_time_availability = get_status_date_time(
                form_data["start_date_time"], form_data["end_date_time"]
            )
            if is_valid(form_data, date_time_availability):
                print("Searching Records... ")
                print("Continuous Plate Records")
                license_plates_continous_order_plate_number = get_filtered_data(
                    form_data, date_time_availability, "continuous"
                )
                print("Random Plate Records")
                license_plate_random_order_plate_number = get_filtered_data(
                    form_data, date_time_availability, "random"
                )
                license_plates = (
                    license_plates_continous_order_plate_number
                    + license_plate_random_order_plate_number
                )
                return render(
                    request,
                    "anpr/plate_search.html",
                    {
                        "license_plates": license_plates,
                        "cameras": cameras,
                        "cameraJSON": json.dumps(cameras),
                        "filter_conditions": form_data,
                    },
                )
        except Exception as e:
            if e.args[0] == "VEHICLE_NO_INVALID":
                print("Invalid Data")
                error = "Vehicle No exists the char limit."
            elif e.args[0] == "DATE_TIME_RANGE_INVALID":
                print("Invalid Data")
                error = "Start Date/Time is greater than End Date/Time."
            else:
                print("error", e.args[0])
                error = "Oops! Something went wrong."

            return render(
                request, "anpr/plate_search.html", {"error": error, "cameras": cameras,}
            )
    else:
        return HttpResponseBadRequest("Bad Request!")


def generate_EXCEL(request):
    form_data = request.GET
    print("form_data", form_data)
    print("Generating excel...")
    try:
        date_time_availability = get_status_date_time(
            form_data["start_date_time"], form_data["end_date_time"]
        )
        if is_valid(form_data, date_time_availability):
            license_plates_continous_order_plate_number = get_filtered_data(
                form_data, date_time_availability, "continuous"
            )
            license_plate_random_order_plate_number = get_filtered_data(
                form_data, date_time_availability, "random"
            )
            contents = (
                license_plates_continous_order_plate_number
                + license_plate_random_order_plate_number
            )
        print("len(contents)", len(contents))
        headers = ["Sl. No", "Camera Name", "Plate Number", "Capture Time", "Image"]
        filename = "vehicle_lists.xlsx"
        create_excel(filename, contents, headers)
    except xlsxwriter.exceptions.FileCreateError as e:
        # For Python 3 use input() instead of raw_input().
        print("Excel Creation Error")
        decision = raw_input(
            "Exception caught in workbook.close(): %s\n"
            "Please close the file if it is open in Excel.\n"
            "Try to write file again? [Y/n]: " % e
        )
        return HttpResponseBadRequest(decision)
    except Exception as e:
        print("Invalid Filter Data")
        return HttpResponseBadRequest("Invalid Filter Data")
    print("Excel generated successfully.")
    return HttpResponse("Success")

oldanpr/templates/anpr/latest5.html
{% load static %} {% for lp in licensePlates %}
<div
  class="latest"
  onclick="openFullImage('{% static lp.fullimage %}', '{{lp.number_plate_number}}')"
>
  <span id="latestCount" style="display: none;">{{count}}</span>
  <div class="snap">
    <img src="{% static lp.image %}" width="100%" height="150px" />
  </div>
  <div class="output">{{lp.number_plate_number}}</div>
</div>
{% endfor %}

oldanpr/templates/anpr/plate_search copy.html
<!DOCTYPE html>
<html>
  <head>
    {% load static %}
    <title>ANPR</title>
    <script src="https://api.tiles.mapbox.com/mapbox-gl-js/v1.8.1/mapbox-gl.js"></script>
    <link
      href="https://api.tiles.mapbox.com/mapbox-gl-js/v1.8.1/mapbox-gl.css"
      rel="stylesheet"
    />
    <link
      href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,700"
      rel="stylesheet"
    />

    <link href="{% static 'anpr/css/center.css' %}" rel="stylesheet" />
    <link href="{% static 'anpr/css/index.css' %}" rel="stylesheet" />

    <link
      rel="stylesheet"
      type="text/css"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/css/bootstrap-datetimepicker.min.css"
    />

    <script
      type="text/javascript"
      src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"
    ></script>
    <script
      type="text/javascript"
      src="https://cdn.jsdelivr.net/momentjs/2.14.1/moment.min.js"
    ></script>
    <script
      type="text/javascript"
      src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"
    ></script>
    <script
      type="text/javascript"
      src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/js/bootstrap-datetimepicker.min.js"
    ></script>

    <style>
      html,
      body {
        height: 100%;
        border: 2px solid #111111;
      }
    </style>
  </head>
  <body style="height: 100%;">
    <div style="display: flex; flex-direction: row; height: 100%;">
      <div class="sidenav">
        <div class="company">
          <img
            style="position: absolute; left: 0;"
            src="{% static 'anpr/images/cctv.png' %}"
          />
          <span style="text-align: center;">ARIMA</span>
        </div>
        <div class="activity">
          <a href="{% url 'anpr:index' %}">Dashboard</a>
          <a href="{% url 'anpr:plate_search' %}" style="color: #f1f1f1;"
            >Plate Search</a
          >
          <a>Vaahan Search</a>
        </div>
      </div>
      <div style="width: 80%; border: groove;">
        <form
          class="form-container"
          action="{% url 'anpr:plate_search' %}"
          method="get"
        >
          {%csrf_token%}
          <div class="form-flex-container">
            <div class="form-flex-element">
              <label>
                Vehicle No
              </label>
              <input name="vehicle_no" type="text" />
            </div>
            <div class="form-flex-element">
              <label>
                Camera Name
              </label>
              <select name="selected_camera" id="cameras">
                {% for camera in cameras %}
                <option value="{{ camera.id }}">{{camera.name}}</option>
                {% endfor %}
              </select>
            </div>
            <div class="form-flex-element">
              <div class="input-group date" id="from">
                <label>
                  Start Date/Time
                </label>
                <input type="text" name="start_date_time" />
                <span class="input-group-addon">
                  <span class="glyphicon glyphicon-calendar"></span>
                </span>
              </div>
            </div>
            <div class="form-flex-element">
              <div class="input-group date" id="to">
                <label>
                  End Date/Time
                </label>
                <input class="input" type="text" name="end_date_time" />
                <span class="input-group-addon">
                  <span class="glyphicon glyphicon-calendar"></span>
                </span>
              </div>
            </div>
            <script type="text/javascript">
              $(function () {
                $("#from").datetimepicker({
                  format: "YYYY-MM-DD HH:mm:ss",
                });
                $("#to").datetimepicker({
                  format: "YYYY-MM-DD HH:mm:ss",
                });
              });
            </script>
          </div>
          {% if error %}
          <script>
            alert("{{ error }}");
          </script>
          {% endif %}
          <div class="search-container">
            <input type="submit" value="Search" />
          </div>
        </form>
        <div class="table-button-container">
          <div style="width: 100%; height: 10%; text-align: center;">
            <h2>Vehicle List</h2>
          </div>
          <div class="table-container">
            <table>
              <thead class="fixed-header">
                <tr>
                  <th width="20%">Sl.No</th>
                  <th>Camera Name</th>
                  <th>Capture Time</th>
                  <th>Plate Number</th>
                  <th>Image</th>
                </tr>
              </thead>
              <tbody class="scroll-content">
                {% for lp in license_plates %}
                <tr>
                  <td>{{lp.slno}}</td>
                  <td>{{lp.camera_name}}</td>
                  <td>{{lp.capture_time}}</td>
                  <td>{{lp.plate_number}}</td>
                  <td>
                    <img
                      src="{% static lp.image_path %}"
                      width="100%"
                      height="150px"
                    />
                  </td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
          <div class="button-flex-container">
            <button onclick="generate_excel()">Export Excel</button>
            <script type="text/javascript">
              function generate_excel() {
                console.log("Requesting for excel export...");
                var params =
                  "?vehicle_no={{ filter_conditions.vehicle_no }}&selected_camera={{ filter_conditions.selected_camera }}&start_date_time={{ filter_conditions.start_date_time }}&end_date_time={{ filter_conditions.end_date_time }}";
                var xhttp = new XMLHttpRequest();
                xhttp.onreadystatechange = function () {
                  if (this.readyState == 4 && this.status == 200) {
                    alert("Excel exported successfully.");
                  } else if (this.readyState == 4 && this.status == 400) {
                    alert("Oops! Exporting excel failed. Try again.");
                  }
                };
                xhttp.open(
                  "GET",
                  "{% url 'anpr:generate_excel' %}" + params,
                  true
                );
                xhttp.send();
              }
            </script>
            <button id="trigger-popup">Get Map</button>
            <div class="map-popup">
              <span class="helper"></span>
              <div>
                <div class="popup-close-button">&times;</div>
                <p>Add any HTML content<br />inside the popup box!</p>
              </div>
            </div>
            <script>
              $(window).load(function () {
                $("#trigger-popup").click(function () {
                  $(".map-popup").show();
                });
                $(".map-popup").click(function () {
                  // $('.map-popup').hide();
                });
                $(".popup-close-button").click(function () {
                  $(".map-popup").hide();
                });
              });
            </script>
            <button>Smart Search</button>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>